name: Sync Image to Aliyun  Example
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2.2.0
    #   with:
    #     registry: cnlk-docker.pkg.coding.net
    #     username: docker-1718173689699
    #     password: 2aaff651212ac624e8aa088902e138a4be9497e4
    #     logout: false
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo login -u docker-1718173689699 -p 2aaff651212ac624e8aa088902e138a4be9497e4 cnlk-docker.pkg.coding.net
        skopeo copy docker://docker.io/teddysun/kms:latest docker://cnlk-docker.pkg.coding.net/common/registry//kms:latest
        skopeo copy docker://docker.io/registry:latest docker://cnlk-docker.pkg.coding.net/common/registry//kms:latest
