name: Sync Image to Coding
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2.2.0
    #   with:
    #     registry: cnlk-docker.pkg.coding.net
    #     username: docker-1718173689699
    #     password: 2aaff651212ac624e8aa088902e138a4be9497e4
    #     logout: false
    - name: Use Skopeo Tools Sync Image from Docker Hub
      run: |
        skopeo login -u docker-1718173689699 -p 2aaff651212ac624e8aa088902e138a4be9497e4 cnlk-docker.pkg.coding.net
        skopeo copy docker://docker.io/palw3ey/ye3ipsec:1.1.5 docker://cnlk-docker.pkg.coding.net/common/registry/palw3ey/ye3ipsec:1.1.5
        skopeo copy docker://docker.io/ultralytics/ultralytics:8.3.203-jetson-jetpack5 docker://cnlk-docker.pkg.coding.net/common/registry/ultralytics:8.3.203-jetson-jetpack5
        # skopeo copy docker://docker.io/teddysun/kms:latest docker://cnlk-docker.pkg.coding.net/common/registry/kms:latest
        # skopeo copy docker://docker.io/registry:latest     docker://cnlk-docker.pkg.coding.net/common/registry/registry:latest
        # skopeo copy docker://docker.io/ultralytics/ultralytics:latest  docker://cnlk-docker.pkg.coding.net/common/registry/ultralytics:latest
        # skopeo copy docker://docker.io/openvpn/openvpn-as:latest       docker://cnlk-docker.pkg.coding.net/common/registry/openvpn-as:latest
        # skopeo copy docker://docker.io/ngoduykhanh/wireguard-ui:latest docker://cnlk-docker.pkg.coding.net/common/registry/wireguard-ui:latest
